openlawteam/docs

.editorconfig
.prettierignore
.vscode/settings.json
.vscode/spellright.dict
CODE_OF_CONDUCT.md
README.md
docs/markup-language/README.md
package-lock.json
package.json

There's more we can do to improve this, but for now, it seems we're already ahead of the Paradox site, so we'll likely make life easier but switching over now before any future iterations -- this feels cleaner too, thus will match better with the soon to be launched site redesign.
Discussion, todo list and PR for switching from paradox site to this (including making open source):

Launch checklist

---

.travis.yml

currently the only test is for our prettier formatting, but this should make it easier to check and enforce for third party open source contributions, and pave the way for future tests such as in #7.

add CI for tests

---

docs/api-client/README.md

[issue-21] Add description for sendTxHash

---

docs/api-client/README.md
docs/markup-language/README.md

[issue-27-28] update docs for network selection feature

---

docs/markup-language/README.md

[issue-11] add description for comma separated number formatting

---

docs/api-client/README.md

`filter` is no longer required.

[recentactivity-filters] updates community activity

---

docs/api-client/README.md

closes #52 
wait to merge this until changes to community activity are closer to being deployed to production

update filters for getCommunityActivity

---

docs/markup-language/README.md

add description of two types of annotation syntax

---

docs/getting-started/README.md

* Adds a small, concise section in **Getting Started** on how to use `openlaw` in JS 
* Adds two H2's for reader's benefit, splitting JavaScript and Scala

Ways to use JS

---

package-lock.json
package.json

Note this will likely need to be rebased off #80 (once it is merged) before merging, as tests were broken in master prior.

update dev-deps within semver, fixes  #79

---

docs/api-client/README.md

add options param to uploadContract call

---

docs/sign-store/README.md

I've removed some headings to preserve the orderings from David's document, which was the basis for this. However, I left headings which would still need to be filled in.

Sig alg v1

---

docs/conversion-tool/README.md
docs/review-tool/README.md

Docs:
- Added new doc
- Reviewed the old docs and updated

Added docs for Conversion and Review Tools

---

docs/api-client/README.md
docs/getting-started-overview/README.md
docs/openlaw-elements/README.md
docs/openlaw-object/README.md

This completes `api-client`, `openlaw-object`, and `openlaw-elements` updates.
This partially completes the `getting-started-overview` update. @mcchan1 can you please include the content update for the API tutorial to this file in a separate PR?

Updates for Getting Started section

---

docs/getting-started-overview/README.md

**Commit Summary:**
add link to the OpenLaw Api Tutorial: Get Started with OpenLaw in Minute.
**File Change:**
getting-started/README.md

add api tutorial link to getting-started-overview readme

---

docs/openlaw-elements/README.md

Small updates to add note about `openlaw` dependency and fix formatting.
@jtrein I finally got around to updating this after your README updates in openlawteam/openlaw-elements#50.

OpenLaw Elements updates

---

docs/beginners-guide/README.md

Underlining could be a popular feature for legal agreements so adding to the Beginner's Guide as well.

add underline examples to Beginner's Guide

---

.eslintrc
package-lock.json
package.json

Removes eslint dependencies and config because they aren't being used.

remove eslint dependencies and config

---

.vscode/spellright.dict
docs/openlaw-elements/README.md

**Additions**
* Docs for onValidate
* Docs for Error Messages
* Tip for safe authentication (basically don't authenticate on the client with stored creds)
**Edits**
* General improvements to prop types and explanations
**Remove**
* `inputLikeTextClass` docs

Openlaw elements v1.0.0

---

docs/openlaw-elements/README.md

OpenLaw Elements -> `openlaw` package

My misnomer in Elements docs

---

docs/openlaw-elements/README.md

This is dependent upon the `v1.1.0` release of Elements.

Adds docs for Elements inputExtraTextMap

---

CONTRIBUTING.md
docs/getting-started-overview/README.md

update slack invite link URL

---

docs/api-client/README.md
docs/forms-flows/README.md
docs/openlaw-elements/README.md

Thanks @joshma91 for flagging the issue in your PR #177. We'll close that one and merge this one which updates in a few more places.

update public instance url
